### ISSUE TITLE
Machine Learning Research

### ISSUE THREAD

**Issue by grabl** [graknlabs/research#5]
_This issue was originally posted by @jmsfltchr  on 2018-08-31 17:29_.

Why
To explore the benefits of combining Grakn with Machine Learning
How
Investigate the integration of machine learning with Grakn.
Efforts to include:
- Feature extraction from Grakn (or equivalent)
- Running ML at query-time, triggered by querying, therefore also by reasoning

This issue needs #9, needs #8, needs #4, needs #13

**Comment by jmsfltchr** [comment]
Closing as too generic, marking as solved since #13 is well underway
